### ISSUE TITLE
[BUG] <ENTER ISSUE HERE>

### ISSUE THREAD

**Issue by bpersello** [axperty/storagedelight-fabric#4]
**Description of the bug**
Missing texture on cherry and bamboo furniture

**Screenshots/Errors**
![2024-06-22_19 25 25](https://github.com/axperty/storagedelight-fabric/assets/116444070/9f840901-868b-4d25-a95b-02833c0de9da)
![2024-06-22_19 25 34](https://github.com/axperty/storagedelight-fabric/assets/116444070/b444287c-4739-474e-938d-d837fa80f718)
![2024-06-22_19 25 42](https://github.com/axperty/storagedelight-fabric/assets/116444070/93cbd142-98da-45f2-ac73-265bbefe13e7)

**Mod Version:**
- Version fabric 1.1.1 - 1.20.1

**Additional information**
Only mod back out of ~ 30 with missing texturs / other issues. all APIs are up to date
Java version 'java 22.0.1'

**Comment by axperty** [comment]
Hi bpersello,

This issue is occurring because you are using Farmer's Delight [Fabric], which has been marked as deprecated and will no longer receive updates. Storage Delight is designed to work with the newer and updated port, [Farmer's Delight Refabricated,](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-refabricated) which includes the missing features like cherry and bamboo cabinets from the original mod.

After you update, the textures for those blocks will be displayed correctly. If you have any more questions, feel free to ask here.

Have a good day, 
Axperty.
